language: cpp

dist: xenial

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t laroque/crasher:latest-travis .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push laroque/crasher:latest-travis
