language: cpp

dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - qemu-user-static

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    ## amd64
    - stage: build images
      name: amd64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u amd64 -r debian -t 9 -a amd64 -i laroque/crasher:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm
    - stage: build images
      name: arm32v7
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u arm32v7 -r debian -t 9 -a arm7 -i laroque/crasher:`echo ${TRAVIS_BRANCH} | tr / _`
    ## aarch64
    - stage: build images
      name: aarch64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u aarch64 -r debian -t 9 -a arm7 -i laroque/crasher:`echo ${TRAVIS_BRANCH} | tr / _`
    ## assmble the manifest
    - stage: assemble manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n laroque/crasher:latest-travis
