
language: C++
dist: trusty

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t travis-ci-build-test .
        - docker images
